Kotlin. Homework #1. Task #2
mawekk/kotlin_homeworks pull request #2
Opened 2022-03-02 18:53 UTC by mawekk

2022-03-03 18:17 UTC, GirZ0n requested changes
Ты либо шаришь за котлин (потому что у меня нет замечаний, кроме нескольких небольших), либо код уж сильно подозрительно похож на [`WoWaster`](https://github.com/WoWaster/spbu-kotlin-homeworks/blob/main/src/main/kotlin/homeworks/homework1/task_2.kt).

![image](https://user-images.githubusercontent.com/55441714/156626697-adfff490-0ecb-449b-a47c-09fbbda9438c.png)

2022-03-03 18:17 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/Task2Test.kt
> +    }
Этот тест тоже можно добавить к параметризованным) 
Для создания пустых массивов обычно используют [`emptyList`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/empty-list.html#emptylist).

2022-03-03 18:17 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +fun sieveOfEratosthenes(bound: Int): List<Int> {
А если передадут отрицательное число?) Давай добавим проверку с помощью [`require`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html#require).

2022-03-03 18:17 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/Task2Test.kt
> +internal class Task2Test {
Добавь ещё тест для проверки `require`.

2022-03-03 18:17 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +
Лишний пробел.

2022-03-03 18:23 UTC, GirZ0n commented
@mawekk, я посоветовался с Егором. Считаем, что эта работа списана, поэтому только 0.1 балла (за старания). Если у тебя есть какие-то объяснения, то можешь написать сюда)

2022-03-03 18:28 UTC, mawekk commented
> @mawekk, я посоветовался с Егором. Считаем, что эта работа списана, поэтому только 0.1 балла (за старания). Если у тебя есть какие-то объяснения, то можешь написать сюда)

блин, я так и знала, что так будет, ахах(
дело в том, что когда вы проверили работу Коли, он предложил мне посмотреть ваши комментарии, чтобы оценить как четко вы все расписали (типа того)
поэтому, когда я писала свой код, я старалась не допускать тех ошибок, о которых вы говорили
потом Коля помогал мне решить проблему с версией котлина, и мы заметили что код реально очень похож, однако сама реализация у нас обоих взята с вики, так что вот так :(

2022-03-03 18:39 UTC, GirZ0n commented
@mawekk, ну в общем у тебя есть два варианта:
1) Исправить текущие замечания. Тогда мы примем задание, но только на 0.1 балл.
2) Ты можешь переписать код как-то по-другому. Кажется что есть и другие способы реализовать решето. Но учти, что одну попытку сдачи ты уже потратила.

2022-03-03 18:44 UTC, mawekk commented
хорошо, я поняла
очень грустно, что так получилось, надеюсь, я смогу загладить эту ситуацию 👉👈

2022-03-05 10:05 UTC, GirZ0n requested changes
:+1:

2022-03-05 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        numbers.add(i)
Можно проще: `val numbers = (2..bound).toMutableList()`)

2022-03-05 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +            for (i in current * current..bound step current)
Поставь скобки для лучшей читаемости: `(current * current)`

2022-03-05 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +            for (i in current * current..bound step current)
И оберни само тело функции в фигурные скобки. Да, в данном случае можно без них, но это лучше сделать, чтобы код был согласован.

2022-03-05 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        print("All primes not exceeding $number:\n${primeNumbers.joinToString(separator = " ")}")
Мне кажется лучше разделить этот `print` на два:
```kotlin
println("All primes not exceeding $number:")
println(primeNumbers.joinToString(separator = " "))
```

Так код лучше читается)

2022-03-05 10:05 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/Task2Test.kt
> +        assertThrows<IllegalArgumentException> { sieveOfEratosthenes(-1) }
Давай ещё добавим проверку сообщения исключения. Так как код может кидать одно и тоже исключение, но с разными сообщениями, то это точно будет полезно делать) Вот [тут](https://www.baeldung.com/kotlin/assertfailswith#1-asserting-exception-attributes) написано как можно проверять сообщение.

2022-03-05 19:31 UTC, GirZ0n approved these changes

2022-03-08 10:49 UTC, SpirinEgor requested changes

2022-03-08 10:49 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    for (current in numbers) {
```kotlin
(2..bound).forEach { ... }
```

2022-03-08 10:49 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +            for (i in (current * current)..bound step current) {
И тут давай через forEach

2022-03-10 14:07 UTC, SpirinEgor approved these changes

2022-03-10 14:08 UTC, merged