Kotlin. Homework #1. Task #3
mawekk/kotlin_homeworks pull request #3
Opened 2022-03-06 22:47 UTC by mawekk

2022-03-08 08:18 UTC, illided requested changes

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class Action(val name: String, val firstParameter: Int?, val secondParameter: Int?)
А если параметров будет больше чем два и другого типа? Например если я захочу добавить команду `addManyNumbers(1,2,3,4,5,6,7,8)`

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class Action(val name: String, val firstParameter: Int?, val secondParameter: Int?)
Просто насколько я понимаю тут параметры nullable как раз чтобы пользователь мог новые команды легко добавлять.

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class Action(val name: String, val firstParameter: Int?, val secondParameter: Int?)
И еще: лучше уж сделать какой нибудь Enum где хранятся все возможные команды. Так будет просто их изменять (например в будущем сделать интерфейс на русском или татарском)

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        if ((second!! >= userList.size) or (first!! < 0) or (second < 0)) {
`!!` здесь не нужен. Котлин умеет понимать, что программа кинет ошибку к этому моменту если эти аргументы null

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    private fun swap(first: Int?, second: Int?) {
Да почему вы все делаете swap) В задании написано элемент с позиции `i` переместить на позицию `j`

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +        val second = command.elementAtOrElse(2) { "" }.toIntOrNull()
Так вот зачем нужны nullable параметры! Не, у нас так не принято)
Давай сделаем проверку, а потом с чистой совестью отдадим столько аргументов команде, сколько ей нужно)

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            println("Result: ${storage.newAction(Action(name, first, second)).joinToString(separator = " ")}")
Слишком много логики в одной строчке. В момент дебага крыша поедет, лучше разделить

2022-03-08 08:18 UTC, illided commented on src/test/kotlin/homework/homework1/Task3KtTest.kt
> +    fun `correct commands`() {
Unit тесты на то и unit, что тестируют отдельные компоненты. Так что здесь лучше разделить тесты по командам.

2022-03-08 08:18 UTC, illided commented on src/test/kotlin/homework/homework1/Task3KtTest.kt
> +    fun `incorrect commands`() {
Аналогичное замечание про unit тесты

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +    var command: List<String>
А зачем делать var? Что мешает сделать val но обьявить в теле цикла?

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    private var storage: MutableList<Action> = mutableListOf()
Зачем здесь var а не val?

2022-03-08 08:18 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        return userList
То есть мне обязательно надо будет делать какое то действие и отменять его чтобы получить список? 
Звучит бюрократично как-то...

2022-03-08 11:07 UTC, mawekk commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        if ((second!! >= userList.size) or (first!! < 0) or (second < 0)) {
почему-то ругается, если я пишу через or :(
а если разношу на два if'а, то все хорошо

2022-03-21 11:10 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        if ((second!! >= userList.size) or (first!! < 0) or (second < 0)) {
Потому что `or` это дополнительная надстройка из стандартной библиотеки и компилятор ее так хорошо не знает как `||` и `&`. Использовать почти всегда стоит именно последние

2022-03-21 11:22 UTC, illided requested changes
Очень много замечаний не исправлено. Перед отправкой на review проходись по всем замечаниям еще раз.
В следующий раз зови Егора и если будут какие то вопросы лучше пиши мне в телегу `@illided`, гитхаб уведомления плохо присылает :(

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        if ((action.type != ActionType.UNDO) and (action.type != ActionType.PRINT)) {
Только сейчас заметил что ты используешь `and` и `or`. Лучше по возможности их не использовать, потому что с ними не будет работать smart cast и они не будут лениво выполнятся.

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        if ((action.type != ActionType.UNDO) and (action.type != ActionType.PRINT)) {
Хотя читается конечно лучше, будем надеяться что их полноценно разовьют

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    var type: ActionType? = null
Здесь вроде бы можно заменить на 
`type = ActionType.values().find { it.actionName == name }`

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        throw IllegalArgumentException("unknown command")
Давай заменим на require

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    private var storage: MutableList<Action> = mutableListOf()
До сих пор почему то `var` :)

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +            "add" -> add(action.parameters[0])
Чот не нравится мне как это выглядит... 
Давай вместо этого под все Action сделаем полноценные классы, задача каждого из которых будет выполнять свой конкретный Action.
А storage вообще не будет знать какие там действия существуют

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    private var userList: MutableList<Int> = mutableListOf()
Здесь почему то тоже

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        return userList
Бюрократия все еще не побеждена...

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        val lastAction = storage.lastOrNull() ?: throw IllegalArgumentException("nothing to undo")
Здесь тоже можно сделать `require` следующей строчкой

2022-03-21 11:22 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +    var command: List<String>
Замечание про val осталось

2022-03-21 11:24 UTC, mawekk commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        return userList
так я ж добавила функцию принта :(

2022-03-21 11:33 UTC, illided commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +        return userList
Так ведь твой супер крутой сторадж будут использовать не только в командной строке)
В каком нибудь андроид приложении например захочешь вставить, а как список чисел получать?

2022-03-22 17:29 UTC, SpirinEgor requested changes

2022-03-22 17:29 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
Не очень понял зачем это надо:
1. Информацию об имене и числе аргументов можно вставить в интерфейс Action и спокойно определять в реализациях -- гарантируем, что у каждого действия есть имя
2. Добавление нового Action заставляет нас ещё в enum его указывать, хотя такой процесс регистрации вполне можно ускорить

2022-03-22 17:29 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class PerformedCommandStorage {
Тут скорее надо иметь 2 основные функции:
1. `applyAction` -- применяет действие к листву и сохраняет в стек
2. `undoAction` -- отменяет действие с вершины стека

2022-03-22 17:29 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/task_3.kt
> +        • exit – bye :("""
У таких строк ещё обычно в конце вызывают `.trimIndent()`, чтобы без всяких смещений печаталось. Но это дело вкуса

2022-03-22 18:18 UTC, mawekk commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
<img width="590" alt="image" src="https://user-images.githubusercontent.com/67863401/159548881-cf8beb03-6fd8-4862-93e1-fa2fb4ccdc73.png">
;)

2022-03-22 18:20 UTC, mawekk commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class PerformedCommandStorage {
то есть функцию newAction нужно заменить на эти? или просто добавить для красоты?)

2022-03-23 09:13 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
@illided нужно твоё пояснение. Мне кажется тут речь шла о CLI командах, а не о возможных `Action`. Ну то есть список `swap`, `undo`, `print`, `exit`, по которому ты ищешь ввод пользователя. И вот его надо в ENUM сложить.

2022-03-23 09:14 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +class PerformedCommandStorage {
Вроде того, `newAction` можно и оставить -- она принимает `Action` и применяет его к листу. К ней надо добавить `undoAction`, которое отменяет последнее.

Сейчас у тебя довольно странная логика -- чтобы отменить действие надо передать новое действие...

2022-03-23 09:17 UTC, illided commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
Ну вообще хотелось какую то общую точку где команды могли бы собираться вместе и иметь название, чтобы потом в частности использовать в CLI. Думал попросить сделать sealed классы, но это продвинутая тема для первой домашки)

2022-03-23 10:21 UTC, Ythosa commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
@illided А можете пояснить, какое здесь применение `sealed` классов вы видете?

2022-03-23 10:39 UTC, illided commented on src/main/kotlin/homework/homework1/Actions.kt
> +}
Сделать обработчики команд sealed классами а потом искать нужные с помощью рефлексии. Вроде прикольно, но кажется слишком громоздко)

2022-03-23 12:53 UTC, SpirinEgor commented on src/main/kotlin/homework/homework1/PerformedCommandStorage.kt
> +    }
```kotlin
val list: List<Int>
    get() = userList
```

2022-03-23 13:17 UTC, SpirinEgor approved these changes

2022-03-23 13:29 UTC, merged