Kotlin. Homework #3
mawekk/kotlin_homeworks pull request #5
Opened 2022-04-15 21:06 UTC by mawekk

2022-05-01 10:18 UTC, GirZ0n requested changes
:+1:

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +@Suppress("TooManyFunctions")
Нельзя так делать, рефактори код :)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +@Suppress("TooManyFunctions")
И так нельзя делать :)

2022-05-01 10:18 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework3/AVLTreeKtTest.kt
> +internal class AVLTreeKtTest {
Тестов мало :( Используй параметризованные тесты, чтобы избежать повторения кода)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +    }
Не надо так делать) Преврати эту функцию в `property` с переопределённой функцией `get()`

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +                    rightChild = rightChild?.rotateRight()
Скобочки надо добавить

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +                    leftChild = leftChild?.rotateLeft()
И тут тоже

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +    }
Можно сразу `fun findNode(key: K): AVLNode<K, V>? = when { ... }`

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +            return leftChild?.findMinNode()
```kotlin
fun findMinNode(): AVLNode<K, V> = leftChild?.findMinNode() ?: this
```

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +            return rightChild
скобочки

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    override val values: MutableCollection<V> = mutableSetOf()
Ну тогда можно также переопределить `get` и использовать `traverse`)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
Можно сразу в одну строчку)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
А зачем так сложно?) Можно же сразу `value in values`

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        root = null
А `size` почему не обнуляется? :(

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            }
А зачем здесь else-ветка? Внутри if находится `return`, так что `else` не нужен)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
Можно в одну строчку

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
Можно в одну строчку

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +                        node.leftChild
Скобочки

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +                set.addAll(traverse(left))
`left?.let { set.addAll(traverse(it)) }`

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            set
Здесь тоже самое

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    private fun traverse(node: AVLNode<K, V>?): MutableSet<MutableMap.MutableEntry<K, V>> {
Вообще кажется, что эту функцию можно перенести в ноду, чтобы не передавать её в качестве аргумента

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    fun printTree() {
Опять же нужно везде скобочки добавить)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        val height = root?.height ?: throw IllegalArgumentException("nothing to print: tree is empty")
Кидать исключение просто из-за того, что дерево пусто это супер странно :)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list[level].add("")
Скобочки

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        }
Так у тебя же есть функция `traverse`...

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    fun printTree() {
Вообще создаётся такое ощущение, что вы там устроили конкурс: "Кто красивее выведет дерево" :)

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    fun printTree() {
Кажется, что лучше сделать так, чтобы эта функция возвращала строку, а не печатала всё сразу в stdout. Тогда можно будет переопределить `toString`, где будет вызывать эта функция.

Ещё стоит также обернуть `splitIntoStrings`  и `printTree` в какой-нибудь companion object.

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        val list = mutableListOf<MutableList<String>>()
Плохое название

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        val strings = splitIntoStrings(root, 0, list)
Плохое название

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +        for (i in 0 until height) {
`forEachIndex` по переменной `strings` кажется лучше использовать

2022-05-01 10:18 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +            return leftChild?.findMinNode()
Да и в целом можно тоже сделать `property` из этой функции)

2022-05-06 10:05 UTC, GirZ0n requested changes
:+1:

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLNode.kt
> +    }
В одну строчку можно)

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    override fun containsKey(key: K): Boolean = keys.contains(key)
Хотелось бы, чтобы `containsKey` работало за O(log(n)). Тут можно использовать функцию `get`)

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    } ?: "empty tree"
А зачем здесь такой перенос строк?) Если всё в одной строчке написать, то вроде влезает в предел строки)

2022-05-06 10:05 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework3/AVLTreeTest.kt
> +        assertEquals(false, tree.containsValue(1))
Вообще не очень хорошо использовать сразу несколько `assert` в рамках одного теста, так как если что-то упадёт, то не сразу будет понятно что именно :) Используй лучше параметризованные тесты везде.

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list: MutableList<MutableList<String>>
Не очень хорошее название)

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list: MutableList<MutableList<String>>
И мне кажется, что тут можно обойтись без передавания списка в качестве аргумента. Внутри функции заполняй список и затем его возвращай.

2022-05-06 10:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            level: Int,
Тут можно поставить дефолтное значение, чтобы в строчке 100 не передавать 0.

2022-05-11 11:34 UTC, mawekk commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list: MutableList<MutableList<String>>
у меня же там рекурсия, я чего-то туплю, как это сделать нормально :(

2022-05-16 12:05 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list: MutableList<MutableList<String>>
Я чего-то думал что у тебя там просто массив. Ладно давай оставим так, я не могу придумать как это переписать так, чтобы список не передавался. Может Егор что-то придумает :)

2022-05-16 12:08 UTC, GirZ0n approved these changes
:+1:

2022-05-17 09:15 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            list: MutableList<MutableList<String>>
Кажется единственный адекватный вариант тут --- избавится от object, чтобы `levels` был частью состояния класса, тогда не надо будет его передавать, будет обращение к полю.

Другой вариант, вынести построения такого листа в класс дерева, его можно поддерживать онлайн кажется без особых хлопот.

Но я бы оставил как есть и не заморачивался, не так уж и страшно

2022-05-17 09:15 UTC, SpirinEgor approved these changes

2022-05-17 09:16 UTC, merged